def brainfuck(code: str, inputs: list[str]) -> tuple[str, int, bool]: ...
def minifuck(code: str, inputs: list[str]) -> tuple[str, int, bool]: ...
def rotfuck(code: str, inputs: list[str]) -> tuple[str, int, int]: ...
def circlefuck(cells: list[int], inputs: list[str]) -> tuple[str, int, int, int]: ...
