"""Unit tests for the BrainIf interpreter."""

import io
from contextlib import redirect_stdout
from unittest.mock import patch

from esolangs.interpreters.io import IO
from esolangs.interpreters.tape_based.brainif import run


def run_and_capture(code: list[str], inputs: list[str] | None = None) -> str:
    buffer = io.StringIO()
    with patch("builtins.input", side_effect=inputs or []), redirect_stdout(buffer):
        run(code, IO())
    return buffer.getvalue()


class TestBrainIfBasicCommands:
    def test_increment(self) -> None:
        assert run_and_capture(["if 0 increment", "if 1 output"]) == "\x01"

    def test_output_zero(self) -> None:
        assert run_and_capture(["if 0 output"]) == "\x00"

    def test_conditional_execution(self) -> None:
        # The output line is only executed when the cell holds 1
        assert run_and_capture(["if 1 output"]) == ""

    def test_input(self) -> None:
        assert run_and_capture(["if 0 input", "if 65 output"], inputs=["A"]) == "A"

    def test_move_right(self) -> None:
        code = ["if 0 right", "if 0 increment", "if 1 output"]
        assert run_and_capture(code) == "\x01"

    def test_move_left_clamps_at_zero(self) -> None:
        code = ["if 0 left", "if 0 increment", "if 1 output"]
        assert run_and_capture(code) == "\x01"


class TestBrainIfGeneratedHelloWorld:
    def test_generated_hello_world(self) -> None:
        """Test a program generated by esolangs.tools.text.brainif."""
        from esolangs.tools.text import brainif

        assert run_and_capture(brainif("Hi").splitlines()) == "Hi"

    def test_truth_machine_zero(self) -> None:
        """A 0 input prints 0 and halts.

        The 1 branch (``if 49 goto 2``) loops forever by definition, so only
        the terminating branch is exercised.
        """
        program = [
            "if 0 input",
            "if 48 output",
            "if 48 goto 6",
            "if 49 output",
            "if 49 goto 2",
        ]
        assert run_and_capture(program, inputs=["0"]) == "0"

    def test_unknown_instruction_ignored(self) -> None:
        """Lines without a recognized instruction are ignored."""
        assert run_and_capture(["if 0 output", "if 0 frobnicate"]) == "\x00"

    def test_goto(self) -> None:
        """Goto jumps to the given line number."""
        code = ["if 0 goto 3", "if 0 output", "if 0 increment", "if 1 output"]
        assert run_and_capture(code) == "\x01"

    def test_missing_value_rejected(self) -> None:
        """A line without a value operand is malformed."""
        import pytest

        with pytest.raises(ValueError, match="malformed"):
            run_and_capture(["if"])

    def test_goto_missing_target_rejected(self) -> None:
        """A goto without a target line is malformed."""
        import pytest

        with pytest.raises(ValueError, match="goto requires"):
            run_and_capture(["if 0 goto"])


class TestStepMachine:
    def test_step_tracks_cells_and_cursor(self) -> None:
        from esolangs.interpreters.io import ScriptedIO
        from esolangs.interpreters.tape_based.brainif import _Machine

        machine = _Machine(["if 0 increment", "if 1 output"], ScriptedIO())
        assert (machine.ind, machine.cells) == (0, [0])
        machine.step()  # cell 0 is 0: increment
        assert machine.cells == [1]
        machine.step()  # cell 1 is 1: output
        assert machine.io.getvalue() == "\x01"
        assert machine.halted
        machine.step()  # stepping a halted machine is a no-op
        assert machine.ind == 2

    def test_snapshot_includes_the_input_cursor(self) -> None:
        from esolangs.interpreters.io import ScriptedIO
        from esolangs.interpreters.tape_based.brainif import _Machine

        machine = _Machine(["if 0 input"], ScriptedIO("A"))
        before = machine.snapshot()
        machine.step()  # input reads the line into the cell
        assert machine.snapshot() != before
        assert machine.cells == [ord("A")]
        assert machine.io.position() == 1

    def test_halting_program_is_detected(self) -> None:
        from esolangs.interpreters.io import ScriptedIO
        from esolangs.interpreters.tape_based.brainif import _Machine
        from esolangs.vm import run_until_halt_or_cycle

        assert run_until_halt_or_cycle(_Machine(["if 0 output"], ScriptedIO())) is True

    def test_goto_loop_is_detected_as_a_cycle(self) -> None:
        """A goto back to itself with the cell unchanged loops forever."""
        from esolangs.interpreters.io import ScriptedIO
        from esolangs.interpreters.tape_based.brainif import _Machine
        from esolangs.vm import run_until_halt_or_cycle

        assert run_until_halt_or_cycle(_Machine(["if 0 goto 1"], ScriptedIO())) is False


def test_a_blank_line_is_skipped() -> None:
    """A line with nothing on it advances the counter and does no work.

    Blank lines are how a BrainIf program is spaced out, so they have to be
    stepped over rather than raising the malformed-line error a one-token
    line gets.
    """
    assert run_and_capture(["if 0 increment", "", "   ", "if 1 output"]) == "\x01"
