"""Unit tests for the BrainIf interpreter."""

import io
from contextlib import redirect_stdout
from unittest.mock import patch

from esolangs.interpreters.io import IO
from esolangs.interpreters.tape_based.brainif import run


def run_and_capture(code: list[str], inputs: list[str] | None = None) -> str:
    buffer = io.StringIO()
    with patch("builtins.input", side_effect=inputs or []), redirect_stdout(buffer):
        run(code, IO())
    return buffer.getvalue()


class TestBrainIfBasicCommands:
    def test_increment(self) -> None:
        assert run_and_capture(["if 0 increment", "if 1 output"]) == "\x01"

    def test_output_zero(self) -> None:
        assert run_and_capture(["if 0 output"]) == "\x00"

    def test_conditional_execution(self) -> None:
        # The output line is only executed when the cell holds 1
        assert run_and_capture(["if 1 output"]) == ""

    def test_input(self) -> None:
        assert run_and_capture(["if 0 input", "if 65 output"], inputs=["A"]) == "A"

    def test_move_right(self) -> None:
        code = ["if 0 right", "if 0 increment", "if 1 output"]
        assert run_and_capture(code) == "\x01"

    def test_move_left_clamps_at_zero(self) -> None:
        code = ["if 0 left", "if 0 increment", "if 1 output"]
        assert run_and_capture(code) == "\x01"


class TestBrainIfGeneratedHelloWorld:
    def test_generated_hello_world(self) -> None:
        """Test a program generated by esolangs.tools.generate.brainif."""
        from esolangs.tools.generate import brainif

        assert run_and_capture(brainif("Hi").splitlines()) == "Hi"

    def test_unknown_instruction_ignored(self) -> None:
        """Lines without a recognized instruction are ignored."""
        assert run_and_capture(["if 0 output", "if 0 frobnicate"]) == "\x00"

    def test_goto(self) -> None:
        """Goto jumps to the given line number."""
        code = ["if 0 goto 3", "if 0 output", "if 0 increment", "if 1 output"]
        assert run_and_capture(code) == "\x01"

    def test_missing_value_rejected(self) -> None:
        """A line without a value operand is malformed."""
        import pytest

        with pytest.raises(ValueError, match="malformed"):
            run_and_capture(["if"])

    def test_goto_missing_target_rejected(self) -> None:
        """A goto without a target line is malformed."""
        import pytest

        with pytest.raises(ValueError, match="goto requires"):
            run_and_capture(["if 0 goto"])
