"""Unit tests for the BrainIf interpreter."""

import io
from contextlib import redirect_stdout
from unittest.mock import patch

from esolangs.interpreters.io import IO
from esolangs.interpreters.tape_based.brainif import run


def run_and_capture(code: list[str], inputs: list[str] | None = None) -> str:
    buffer = io.StringIO()
    with patch("builtins.input", side_effect=inputs or []), redirect_stdout(buffer):
        run(code, IO())
    return buffer.getvalue()


class TestBrainIfBasicCommands:
    def test_increment(self) -> None:
        assert run_and_capture(["if 0 increment", "if 1 output"]) == "\x01"

    def test_output_zero(self) -> None:
        assert run_and_capture(["if 0 output"]) == "\x00"

    def test_conditional_execution(self) -> None:
        # The output line is only executed when the cell holds 1
        assert run_and_capture(["if 1 output"]) == ""

    def test_input(self) -> None:
        assert run_and_capture(["if 0 input", "if 65 output"], inputs=["A"]) == "A"

    def test_input_retries_past_blank_lines(self) -> None:
        """A blank line is read again, not stored as the newline it ended.

        ``input`` reads whole lines, and an empty one carries no character
        to take -- so the read repeats until a line has one.  Nothing else
        in the suite feeds a blank line, and the retry is the loop's only
        observable: without it the first empty string would be indexed and
        raise, and a loop entered on the wrong condition would either skip
        the read or never leave it.
        """
        code = ["if 0 input", "if 65 output"]
        assert run_and_capture(code, inputs=["", "", "A"]) == "A"

    def test_move_right(self) -> None:
        code = ["if 0 right", "if 0 increment", "if 1 output"]
        assert run_and_capture(code) == "\x01"

    def test_move_left_clamps_at_zero(self) -> None:
        code = ["if 0 left", "if 0 increment", "if 1 output"]
        assert run_and_capture(code) == "\x01"

    def test_the_walk_out_and_back(self) -> None:
        """Walk out to cell 3 and back, marking each cell on the return.

        Every move here is from a cell other than the origin, which is what
        makes it worth its length: from cell 0 a relative ``right`` and an
        absolute jump to cell 1 agree, and a ``left`` that moves one and
        one that moves two both clamp to 0.  Walking out first separates
        them, and reading two cells at the end shows where the pointer
        actually landed rather than only that it moved.
        """
        code = [
            "if 0 right",  # cell 1
            "if 0 right",  # cell 2
            "if 0 right",  # cell 3
            "if 0 increment",  # cell 3 = 1
            "if 1 left",  # cell 2
            "if 0 increment",  # cell 2 = 1
            "if 1 left",  # cell 1
            "if 0 increment",  # cell 1 = 1
            "if 1 left",  # cell 0, untouched
            "if 0 output",
            "if 0 right",  # cell 1 again
            "if 1 output",
        ]
        assert run_and_capture(code) == "\x00\x01"

    def test_a_new_cell_starts_at_zero(self) -> None:
        """Moving right onto fresh tape appends a zero, not a one."""
        assert run_and_capture(["if 0 right", "if 0 output"]) == "\x00"


class TestBrainIfGeneratedHelloWorld:
    def test_generated_hello_world(self) -> None:
        """Test a program generated by esolangs.tools.text.brainif."""
        from esolangs.tools.text import brainif

        assert run_and_capture(brainif("Hi").splitlines()) == "Hi"

    def test_truth_machine_zero(self) -> None:
        """A 0 input prints 0 and halts.

        The 1 branch (``if 49 goto 2``) loops forever by definition, so only
        the terminating branch is exercised.
        """
        program = [
            "if 0 input",
            "if 48 output",
            "if 48 goto 6",
            "if 49 output",
            "if 49 goto 2",
        ]
        assert run_and_capture(program, inputs=["0"]) == "0"

    def test_unknown_instruction_ignored(self) -> None:
        """Lines without a recognized instruction are ignored."""
        assert run_and_capture(["if 0 output", "if 0 frobnicate"]) == "\x00"

    def test_goto(self) -> None:
        """Goto jumps to the given line number."""
        code = ["if 0 goto 3", "if 0 output", "if 0 increment", "if 1 output"]
        assert run_and_capture(code) == "\x01"

    def test_missing_value_rejected(self) -> None:
        """A line without a value operand is malformed.

        The message is matched in full, and with its casing: a loose
        substring lets the wording drift without any test objecting.
        """
        import pytest

        with pytest.raises(ValueError, match=r"^malformed BrainIf line: if$"):
            run_and_capture(["if"])

    def test_a_value_with_no_command_is_well_formed(self) -> None:
        """Two tokens are enough: ``if 0`` names a value and does nothing.

        This is the other side of the arity guard.  Only a line of fewer
        than two tokens is malformed, so a two-token line has to run --
        and it is the case that separates ``< 2`` from ``< 3``.
        """
        assert run_and_capture(["if 0", "if 0 output"]) == "\x00"

    def test_goto_missing_target_rejected(self) -> None:
        """A goto without a target line is malformed."""
        import pytest

        with pytest.raises(ValueError, match=r"^goto requires a target line$"):
            run_and_capture(["if 0 goto"])


class TestStepMachine:
    def test_step_tracks_cells_and_cursor(self) -> None:
        from esolangs.interpreters.io import ScriptedIO
        from esolangs.interpreters.tape_based.brainif import _Machine

        machine = _Machine(["if 0 increment", "if 1 output"], ScriptedIO())
        assert (machine.ind, machine.cells) == (0, [0])
        machine.step()  # cell 0 is 0: increment
        assert machine.cells == [1]
        machine.step()  # cell 1 is 1: output
        assert machine.io.getvalue() == "\x01"
        assert machine.halted
        machine.step()  # stepping a halted machine is a no-op
        assert machine.ind == 2

    def test_snapshot_includes_the_input_cursor(self) -> None:
        from esolangs.interpreters.io import ScriptedIO
        from esolangs.interpreters.tape_based.brainif import _Machine

        machine = _Machine(["if 0 input"], ScriptedIO("A"))
        before = machine.snapshot()
        machine.step()  # input reads the line into the cell
        assert machine.snapshot() != before
        assert machine.cells == [ord("A")]
        assert machine.io.position() == 1

    def test_halting_program_is_detected(self) -> None:
        from esolangs.interpreters.io import ScriptedIO
        from esolangs.interpreters.tape_based.brainif import _Machine
        from esolangs.vm import run_until_halt_or_cycle

        assert run_until_halt_or_cycle(_Machine(["if 0 output"], ScriptedIO())) is True

    def test_goto_loop_is_detected_as_a_cycle(self) -> None:
        """A goto back to itself with the cell unchanged loops forever."""
        from esolangs.interpreters.io import ScriptedIO
        from esolangs.interpreters.tape_based.brainif import _Machine
        from esolangs.vm import run_until_halt_or_cycle

        assert run_until_halt_or_cycle(_Machine(["if 0 goto 1"], ScriptedIO())) is False


def test_a_blank_line_is_skipped() -> None:
    """A line with nothing on it advances the counter and does no work.

    Blank lines are how a BrainIf program is spaced out, so they have to be
    stepped over rather than raising the malformed-line error a one-token
    line gets.

    Where the blank sits matters, in two ways.  A blank at the top of the
    program is stepped identically by an advance, a reset to line 1, and a
    double advance, so it has to follow a line that has already run.  And a
    run of consecutive blanks hides a double advance -- skipping two blanks
    still lands on a line that does nothing -- so a single blank is put
    directly before the output, where skipping two would skip the output
    itself.  The run of blanks is kept as its own case.
    """
    assert run_and_capture(["if 0 increment", "", "if 1 output"]) == "\x01"
    assert run_and_capture(["if 0 increment", "", "   ", "if 1 output"]) == "\x01"
