name = "esolangs"
version = "0.1.0"
defaultTargets = ["Esolangs", "albabet", "excon", "bfpda", "seventy_four"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.32.2"

[[lean_lib]]
name = "Esolangs"

[[lean_exe]]
name = "albabet"
root = "AlbabetMain"

[[lean_exe]]
name = "excon"
root = "ExconMain"

[[lean_exe]]
name = "bfpda"
root = "BfpdaMain"

[[lean_exe]]
name = "seventy_four"
root = "SeventyFourMain"
