"""Boolean-function program generators (re-exported from the boolean package).

Each generator builds a program that reads n boolean inputs and prints the
truth-table result for the combination it is given; the input count ``n``
is implied by the table length (``2**n`` entries), so the generators take
only the table.  The parameterized generators (``bio``, ``back``,
``nocomment``, ``bfpda``, ``dotlang``) instead emit a template the harness
instantiates per input combination.

The generators live in ``esolangs.tools.boolean``, split by language family
(``register``, ``stack``, ``tape``, ``other``, ``parameterized``); this
module re-exports them for compatibility.
"""

from esolangs.tools.boolean.other import (
    abcdirection,
    between,
    bit_tilde,
    clockwise,
    container,
    forbin_boolean,
    laserfuck,
    myscript,
    nevermind,
    suptiftam,
    taglate,
    three_x,
    ztoalc_l_boolean,
)
from esolangs.tools.boolean.parameterized import (
    a_painter_ant,
    arrowqueue,
    back,
    bfpda,
    bio,
    bitdeque,
    dotlang,
    eval,  # noqa: A004 - the language is named "Eval"
    instantiate,
    instantiate_wii2d_tree,
    lamfunc,
    minsky_swap,
    nocomment,
    ram0,
    wii2d,
    wii2d_tree,
)
from esolangs.tools.boolean.register import (
    addsubjump,
    collatz_multiverse,
    decleq,
    dig,
    point_break,
    polynomial,
    qoibl,
    sophie,
)
from esolangs.tools.boolean.stack import bfstack, forth, grapheme, modulous, unsquare
from esolangs.tools.boolean.tape import (
    basicfuck,
    bf_tree,
    brainfuck,
    brainif,
    circlefuck,
    circlefuck_byte,
    dimensional,
    dimensional_tree,
    jaune,
    jaune_multiply,
    painfuck,
    rotfuck,
    sbleq,
    six_five,
    six_five_arithmetic,
    three_d_brainfuck,
)

__all__ = [
    "BOOLEAN",
    "a_painter_ant",
    "abcdirection",
    "addsubjump",
    "arrowqueue",
    "back",
    "basicfuck",
    "between",
    "bf_tree",
    "bfpda",
    "bfstack",
    "bio",
    "bit_tilde",
    "bitdeque",
    "brainfuck",
    "brainif",
    "circlefuck",
    "circlefuck_byte",
    "clockwise",
    "collatz_multiverse",
    "container",
    "decleq",
    "dig",
    "dimensional",
    "dimensional_tree",
    "dotlang",
    "eval",
    "forbin_boolean",
    "forth",
    "grapheme",
    "instantiate",
    "instantiate_wii2d_tree",
    "jaune",
    "jaune_multiply",
    "lamfunc",
    "laserfuck",
    "minsky_swap",
    "modulous",
    "myscript",
    "nevermind",
    "nocomment",
    "painfuck",
    "point_break",
    "polynomial",
    "qoibl",
    "ram0",
    "rotfuck",
    "sbleq",
    "six_five",
    "six_five_arithmetic",
    "sophie",
    "suptiftam",
    "taglate",
    "three_d_brainfuck",
    "three_x",
    "unsquare",
    "wii2d",
    "wii2d_tree",
    "ztoalc_l_boolean",
]

# Display names of the languages that have a boolean-function generator.
# Single source of truth for the capability matrix and the public API's
# ``describe``.
BOOLEAN: frozenset[str] = frozenset(
    {
        "3x",
        "ABCDirection",
        "A Painter Ant",
        "AddSubJump",
        "3D Brainfuck",
        "6-5",
        "ArrowQueue",
        "Back",
        "Basicfuck",
        "Between",
        "BF-PDA",
        "Bitdeque",
        "brainfuck",
        "BFStack",
        "BIO",
        "bit~",
        "BrainIf",
        "Circlefuck",
        "Clockwise",
        "Collatz Multiverse",
        "Container",
        "Dig",
        "Dimensional",
        "Decleq",
        "Dotlang",
        "Eval",
        "Forbin",
        "Forþ",
        "Grapheme",
        "Jaune",
        "Lamfunc",
        "LaserFuck",
        "Minsky Swap",
        "Modulous",
        "MyScript",
        "Nevermind",
        "NoComment",
        "Painfuck",
        "Point Break",
        "Polynomial",
        "Qoibl",
        "RAM0",
        "ROTfuck",
        "S*bleq",
        "Sophie",
        "Suptiftam",
        "Taglate",
        "Unsquare",
        "WII2D",
        "ZTOALC L",
    }
)
