"""Boolean-function program generators (re-exported from the boolean package).

Each generator builds a program that reads n boolean inputs and prints the
truth-table result for the combination it is given; the input count ``n``
is implied by the table length (``2**n`` entries), so the generators take
only the table.  The parameterized generators (``bio``, ``back``,
``nocomment``, ``bfpda``) instead emit a template the harness
instantiates per input combination.

The generators live in ``esolangs.tools.boolean``, split by language family
(``register``, ``stack``, ``tape``, ``other``, ``parameterized``); this
module re-exports them for compatibility.
"""

from esolangs.tools.boolean.circuit_diagram import circuit_diagram
from esolangs.tools.boolean.other import (
    between,
    bit_tilde,
    clockwise,
    container,
    flowchart,
    forbin_boolean,
    laserfuck,
    myscript,
    nevermind,
    streetcode,
    suptiftam,
    taglate,
    three_x,
    ztoalc_l_boolean,
)
from esolangs.tools.boolean.parameterized import (
    a_painter_ant,
    arrowqueue,
    back,
    bfpda,
    bio,
    bitdeque,
    cod,
    eval,  # noqa: A004 - the language is named "Eval"
    home_row,
    instantiate,
    lamfunc,
    minsky_swap,
    nocomment,
    ram0,
    wii2d,
)
from esolangs.tools.boolean.register import (
    addsubjump,
    collatz_multiverse,
    decleq,
    dig,
    point_break,
    polynomial,
    qoibl,
    sophie,
)
from esolangs.tools.boolean.stack import bfstack, forth, grapheme, modulous, unsquare
from esolangs.tools.boolean.tape import (
    basicfuck,
    bf_tree,
    brainfuck,
    brainif,
    circlefuck,
    circlefuck_byte,
    dimensional,
    dimensional_tree,
    factor,
    jaune,
    jaune_multiply,
    painfuck,
    rotfuck,
    sbleq,
    six_five,
    six_five_arithmetic,
    suffolk,
    three_d_brainfuck,
)

__all__ = [
    "BOOLEAN",
    "a_painter_ant",
    "addsubjump",
    "arrowqueue",
    "back",
    "basicfuck",
    "between",
    "bf_tree",
    "bfpda",
    "bfstack",
    "bio",
    "bit_tilde",
    "bitdeque",
    "brainfuck",
    "brainif",
    "circlefuck",
    "circlefuck_byte",
    "circuit_diagram",
    "clockwise",
    "cod",
    "collatz_multiverse",
    "container",
    "decleq",
    "dig",
    "dimensional",
    "dimensional_tree",
    "eval",
    "factor",
    "flowchart",
    "forbin_boolean",
    "forth",
    "grapheme",
    "home_row",
    "instantiate",
    "jaune",
    "jaune_multiply",
    "lamfunc",
    "laserfuck",
    "minsky_swap",
    "modulous",
    "myscript",
    "nevermind",
    "nocomment",
    "painfuck",
    "point_break",
    "polynomial",
    "qoibl",
    "ram0",
    "rotfuck",
    "sbleq",
    "six_five",
    "six_five_arithmetic",
    "sophie",
    "streetcode",
    "suffolk",
    "suptiftam",
    "taglate",
    "three_d_brainfuck",
    "three_x",
    "unsquare",
    "wii2d",
    "ztoalc_l_boolean",
]

# Display names of the languages that have a boolean-function generator.
# Single source of truth for the capability matrix and the public API's
# ``describe``.
BOOLEAN: frozenset[str] = frozenset(
    {
        "3x",
        "A Painter Ant",
        "AddSubJump",
        "3D Brainfuck",
        "6-5",
        "ArrowQueue",
        "Back",
        "Basicfuck",
        "Between",
        "BF-PDA",
        "Bitdeque",
        "brainfuck",
        "BFStack",
        "BIO",
        "bit~",
        "BrainIf",
        "Circlefuck",
        "Circuit Diagram",
        "Clockwise",
        "COD",
        "Collatz Multiverse",
        "Container",
        "Dig",
        "Dimensional",
        "Decleq",
        "Eval",
        "Factor",
        "Flowchart",
        "Forbin",
        "Forþ",
        "Grapheme",
        "Home Row",
        "Jaune",
        "Lamfunc",
        "LaserFuck",
        "Minsky Swap",
        "Modulous",
        "MyScript",
        "Nevermind",
        "NoComment",
        "Painfuck",
        "Point Break",
        "Polynomial",
        "Qoibl",
        "RAM0",
        "ROTfuck",
        "S*bleq",
        "Sophie",
        "Streetcode",
        "Suffolk",
        "Suptiftam",
        "Taglate",
        "Unsquare",
        "WII2D",
        "ZTOALC L",
    }
)
