"""Run every committed example program and check its output.

The hello-world examples are generated by ``esolangs.tools.text`` and
committed under ``examples/hello-world``.  Each is run through its interpreter
and must reproduce ``Hello, World!``; a companion test keeps the files in sync
with whatever the generators currently produce.  The hand-written cat and
truth-machine examples under ``examples/cat`` and ``examples/truth-machine``
are also run.  A truth machine echoes ``0`` and halts when given ``0``; its
``1`` branch loops forever by design and is not executed.
"""

import importlib
import io
from contextlib import redirect_stdout, suppress
from pathlib import Path
from unittest.mock import patch

import pytest

from esolangs.interpreters.io import IO
from esolangs.registry import LANGUAGES
from esolangs.tools.boolean.examples import BOOLEAN_EXAMPLES as BOOLEAN_GENERATED
from esolangs.tools.boolean.examples import HAND_WRITTEN

EXAMPLES_DIR = Path(__file__).parent.parent / "examples" / "hello-world"


def _file_name(display_name: str) -> str:
    return display_name.lower().replace(" ", "-")


# example file stem -> (interpreter module, split lines, kwargs), derived
# from the language registry.
EXAMPLES = {
    _file_name(lang.name): (lang.interpreter, lang.split, dict(lang.kwargs))
    for lang in LANGUAGES.values()
    if lang.generator and lang.interpreter
}

# container halts by calling sys.exit(0)
EXITS = {"container"}


def run_example(name: str) -> str:
    module, splitlines, kwargs = EXAMPLES[name]
    run = importlib.import_module("esolangs.interpreters." + module).run
    program = (EXAMPLES_DIR / f"{name}.txt").read_text(encoding="utf-8").rstrip("\n")
    argument = program.splitlines() if splitlines else program

    buffer = io.StringIO()
    try:
        with redirect_stdout(buffer):
            run(argument, io=IO(), **kwargs)
    except SystemExit:
        assert name in EXITS, f"{name} exited unexpectedly"
    return buffer.getvalue()


@pytest.mark.parametrize("name", sorted(EXAMPLES))
def test_hello_world_example(name: str) -> None:
    expected = "Hello, World!\n" if name == "nevermind" else "Hello, World!"
    assert run_example(name) == expected


def test_example_files_match_generator() -> None:
    """The committed examples are exactly what the generators produce today."""
    generators = {
        _file_name(lang.name): lang.generator
        for lang in LANGUAGES.values()
        if lang.generator and lang.interpreter
    }
    for name, generator in generators.items():
        path = EXAMPLES_DIR / f"{name}.txt"
        assert path.read_text(encoding="utf-8") == generator("Hello, World!")


def test_no_orphan_hello_world_examples() -> None:
    """Every hello-world file belongs to a language that still has a generator.

    The other tests derive their parameters from the registry, so a file for a
    language that was removed is never collected and cannot fail.  Scanning the
    directory is what catches it.
    """
    committed = {path.stem for path in EXAMPLES_DIR.glob("*.txt")}
    assert committed - set(EXAMPLES) == set(), "example files with no generator"
    assert set(EXAMPLES) - committed == set(), "generators with no example file"


def test_multiply_example_matches_generator() -> None:
    """The committed multiply program is exactly what the generator produces."""
    from esolangs.tools.boolean import jaune_multiply

    path = BASE_DIR / "examples" / "multiply" / "jaune.txt"
    assert path.read_text(encoding="utf-8") == jaune_multiply()


@pytest.mark.parametrize("name", sorted(BOOLEAN_GENERATED))
def test_boolean_example_matches_generator(name: str) -> None:
    """Each committed boolean program is what its generator produces today.

    The counterpart of :func:`test_example_files_match_generator` for the
    boolean examples; refresh them with
    ``python scripts/write_boolean_examples.py``.
    """
    path = BASE_DIR / "examples" / "boolean" / f"{name}.txt"
    committed = path.read_text(encoding="utf-8").rstrip("\n")
    assert committed == BOOLEAN_GENERATED[name].build().rstrip("\n")


def test_boolean_examples_cover_every_committed_file() -> None:
    """Every file in examples/boolean is accounted for, and vice versa."""
    on_disk = {p.stem for p in (BASE_DIR / "examples" / "boolean").glob("*.txt")}
    assert on_disk == set(BOOLEAN_GENERATED) | set(HAND_WRITTEN)


# name -> (interpreter module, input lines, expected output, split lines)
CAT_EXAMPLES = {
    "between": ("register_based.between", ["hi"], "hi", True),
    "nevermind": ("register_based.nevermind", ["hi"], "hi\n", True),
    "6-5": ("tape_based.six_five", ["h"], "h", False),
    "modulous": ("stack_based.modulous", ["hi"], "hi", False),
    "suptiftam": ("other.suptiftam", ["hi"], "hi", False),
}

TRUTH_MACHINE_EXAMPLES = {
    "between": ("register_based.between", ["0"], "0", True),
    "brainif": ("tape_based.brainif", ["0"], "0", True),
    "circlefuck": ("tape_based.circlefuck", ["0"], "0", False),
    "factor": ("tape_based.factor", ["0"], "0", False),
    "forbin": ("other.forbin", ["0"], "0", False),
    "modulous": ("stack_based.modulous", ["0"], "0", False),
    "suptiftam": ("other.suptiftam", ["0"], "0", False),
}

BASE_DIR = Path(__file__).parent.parent


# name -> (interpreter module, input lines, expected output, split lines)
# The multiply examples feed two sentinel-delimited decimal operands: the
# digits of the first operand, a "*" line, the digits of the second, and a
# "#" line.  The program prints their product (see docs/walls.md).
MULTIPLY_EXAMPLES = {
    "jaune": ("tape_based.jaune", ["1", "2", "*", "3", "4", "#"], "408", False),
}

# The boolean examples demonstrate a language's boolean-function capability
# that is not an I/O truth machine (see docs/walls.md).  Unlike the tables
# above, they are derived from ``esolangs.tools.boolean.examples``, which
# records for each committed program the generator, truth table, and input
# combination that produced it -- so the files stay in sync with the
# generators the way the hello-world examples do.
#
# The input-reading languages take their bits on stdin; the parameterized
# ones (see ``esolangs.tools.boolean.parameterized``) have the bits embedded
# in the program text and read no input.  ArrowQueue and Point Break have no
# output at all: their result is the halt-vs-loop convention, so only the
# terminating (`0`) branch is committed -- the `1` branch loops forever by
# definition and is not executed.
BOOLEAN_EXAMPLES = {
    stem: (ex.interpreter, list(ex.inputs), ex.expected, ex.split, dict(ex.kwargs))
    for stem, ex in BOOLEAN_GENERATED.items()
} | {
    stem: (interpreter, list(inputs), expected, split, {})
    for stem, (interpreter, inputs, expected, split) in HAND_WRITTEN.items()
}


def run_with_input(name: str, subdir: str) -> None:
    kwargs: dict[str, int] = {}
    if subdir == "multiply":
        module, inputs, expected, splitlines = MULTIPLY_EXAMPLES[name]
    elif subdir == "boolean":
        module, inputs, expected, splitlines, kwargs = BOOLEAN_EXAMPLES[name]
    else:
        examples = CAT_EXAMPLES if subdir == "cat" else TRUTH_MACHINE_EXAMPLES
        module, inputs, expected, splitlines = examples[name]
    run = importlib.import_module("esolangs.interpreters." + module).run
    program = (
        (BASE_DIR / "examples" / subdir / f"{name}.txt")
        .read_text(encoding="utf-8")
        .rstrip("\n")
    )
    argument = program.splitlines() if splitlines else program

    buffer = io.StringIO()
    # Container halts by calling sys.exit(0), like its hello-world example.
    with (
        patch("builtins.input", side_effect=inputs),
        redirect_stdout(buffer),
        suppress(SystemExit),
    ):
        run(argument, io=IO(), **kwargs)
    assert buffer.getvalue() == expected


@pytest.mark.parametrize("name", sorted(CAT_EXAMPLES))
def test_cat_example(name: str) -> None:
    run_with_input(name, "cat")


@pytest.mark.parametrize("name", sorted(TRUTH_MACHINE_EXAMPLES))
def test_truth_machine_example(name: str) -> None:
    run_with_input(name, "truth-machine")


@pytest.mark.parametrize("name", sorted(BOOLEAN_EXAMPLES))
def test_boolean_example(name: str) -> None:
    run_with_input(name, "boolean")


@pytest.mark.parametrize("name", sorted(MULTIPLY_EXAMPLES))
def test_multiply_example(name: str) -> None:
    run_with_input(name, "multiply")
