"""Run every committed example program and check its output.

The hello-world examples are generated by ``esolangs.tools.generate`` and
committed under ``examples/hello-world``.  Each is run through its interpreter
and must reproduce ``Hello, World!``; a companion test keeps the files in sync
with whatever the generators currently produce.  The hand-written cat and
truth-machine examples under ``examples/cat`` and ``examples/truth-machine``
are also run.  A truth machine echoes ``0`` and halts when given ``0``; its
``1`` branch loops forever by design and is not executed.
"""

import importlib
import io
from contextlib import redirect_stdout
from pathlib import Path
from unittest.mock import patch

import pytest

EXAMPLES_DIR = Path(__file__).parent.parent / "examples" / "hello-world"

# name -> (interpreter module under esolangs.interpreters, split lines, kwargs)
EXAMPLES = {
    "6-5": ("tape_based.6-5", False, {}),
    "ascii-art": ("tape_based.ascii-art", False, {}),
    "bfstack": ("stack_based.bfstack", False, {}),
    "bio": ("register_based.bio", False, {}),
    "brainif": ("tape_based.brainif", True, {}),
    "clockwise": ("other.clockwise", True, {}),
    "container": ("other.container", True, {}),
    "dig": ("register_based.dig", True, {}),
    "dotlang": ("register_based.dotlang", True, {}),
    "eval": ("stack_based.eval", False, {}),
    "excon": ("tape_based.excon", False, {}),
    "huf": ("register_based.huf", False, {}),
    "mammalian": ("tape_based.mammalian", False, {}),
    "minifuck": ("tape_based.minifuck", False, {}),
    "modulous": ("stack_based.modulous", False, {}),
    "nevermind": ("other.nevermind", True, {}),
    "polynomial": ("register_based.polynomial", False, {}),
    "qoibl": ("register_based.qoibl", True, {}),
    "sophie": ("register_based.sophie", False, {}),
    "suffolk": ("tape_based.suffolk", False, {"limit": 1}),
    "temporary": ("stack_based.temporary", False, {}),
    "wii2d": ("register_based.WII2D", True, {}),
    "ztoalc": ("other.ztoalc", True, {}),
}

# container halts by calling sys.exit(0)
EXITS = {"container"}


def run_example(name: str) -> str:
    module, splitlines, kwargs = EXAMPLES[name]
    run = importlib.import_module("esolangs.interpreters." + module).run
    program = (EXAMPLES_DIR / f"{name}.txt").read_text(encoding="utf-8").rstrip("\n")
    argument = program.splitlines() if splitlines else program

    buffer = io.StringIO()
    try:
        with redirect_stdout(buffer):
            run(argument, **kwargs)
    except SystemExit:
        assert name in EXITS, f"{name} exited unexpectedly"
    return buffer.getvalue()


@pytest.mark.parametrize("name", sorted(EXAMPLES))
def test_hello_world_example(name: str) -> None:
    expected = "Hello, World!\n" if name == "nevermind" else "Hello, World!"
    assert run_example(name) == expected


def test_example_files_match_generator() -> None:
    """The committed examples are exactly what the generators produce today."""
    import esolangs.tools.generate as gen

    generators = {
        "6-5": gen.six_five,
        "ascii-art": gen.ascii_art,
        "bfstack": gen.bfstack,
        "bio": gen.bio,
        "brainif": gen.brainif,
        "clockwise": gen.clockwise,
        "container": gen.container,
        "dig": gen.dig,
        "dotlang": gen.dotlang,
        "eval": gen.eval,
        "excon": gen.excon,
        "huf": gen.huf,
        "mammalian": gen.mammalian,
        "minifuck": gen.minifuck,
        "modulous": gen.modulous,
        "nevermind": gen.nevermind,
        "polynomial": gen.polynomial,
        "qoibl": gen.qoibl,
        "sophie": gen.sophie,
        "suffolk": gen.suffolk,
        "temporary": gen.temporary,
        "wii2d": gen.wii2d,
        "ztoalc": gen.ztoalc,
    }
    for name, generator in generators.items():
        path = EXAMPLES_DIR / f"{name}.txt"
        assert path.read_text(encoding="utf-8") == generator("Hello, World!")


# name -> (interpreter module, input lines, expected output, split lines)
CAT_EXAMPLES = {
    "nevermind": ("other.nevermind", ["hi"], "hi\n", True),
    "6-5": ("tape_based.6-5", ["h"], "h", False),
    "modulous": ("stack_based.modulous", ["hi"], "hi", False),
}

TRUTH_MACHINE_EXAMPLES = {
    "modulous": ("stack_based.modulous", ["0"], "0", False),
    "brainif": ("tape_based.brainif", ["0"], "0", True),
}

BASE_DIR = Path(__file__).parent.parent


def run_with_input(name: str, subdir: str) -> None:
    examples = CAT_EXAMPLES if subdir == "cat" else TRUTH_MACHINE_EXAMPLES
    module, inputs, expected, splitlines = examples[name]
    run = importlib.import_module("esolangs.interpreters." + module).run
    program = (
        (BASE_DIR / "examples" / subdir / f"{name}.txt")
        .read_text(encoding="utf-8")
        .rstrip("\n")
    )
    argument = program.splitlines() if splitlines else program

    buffer = io.StringIO()
    with patch("builtins.input", side_effect=inputs):
        with redirect_stdout(buffer):
            run(argument)
    assert buffer.getvalue() == expected


@pytest.mark.parametrize("name", sorted(CAT_EXAMPLES))
def test_cat_example(name: str) -> None:
    run_with_input(name, "cat")


@pytest.mark.parametrize("name", sorted(TRUTH_MACHINE_EXAMPLES))
def test_truth_machine_example(name: str) -> None:
    run_with_input(name, "truth-machine")
