"""Write the committed examples from their generators.

Every committed example is exactly what its generator produces today: the
boolean programs under ``examples`` come from the boolean generators.
``tests/scripts/test_examples.py`` asserts that; run this script to refresh
the files after a generator changes.

    python scripts/generate.py examples           # every set
    python scripts/generate.py examples boolean   # just one set
"""

import argparse
import pathlib
from collections.abc import Iterator

from esolangs._program import Program
from esolangs.raster import Raster
from esolangs.registry import LANGUAGES, canonical_id
from esolangs.tools.examples import BOOLEAN_EXAMPLES, BooleanExample

_BY_ID = {lang.id: name for name, lang in LANGUAGES.items()}

ROOT = pathlib.Path(__file__).parents[3]
EXAMPLES = ROOT / "src" / "esolangs" / "examples"


def boolean_programs() -> Iterator[tuple[str, Program]]:
    """Yield ``(stem, program)`` for every boolean example."""
    for stem, example in sorted(BOOLEAN_EXAMPLES.items()):
        yield stem, example.build(balance=True)


def _display_name(stem: str) -> str:
    """Return the registry display name for an example's filename stem."""
    return _BY_ID.get(canonical_id(stem.replace("-", " ")), stem)


def _logical_row(stem: str, example: BooleanExample) -> str:
    """Return the input row as plain bits, however the language spells it.

    The Input column shows the *encoded* stdin, which made this table
    unusable for judging an example programmatically: a reader had to work
    back from ``% A`` to ``10`` for Grapheme, and from the decimal ``1`` to
    ``01`` for Fargo.  A template language already records its bits; a
    reading one does not, so the row is recovered by encoding each candidate
    and keeping the one that reproduces the stored input.

    That search is also a check.  There are only ``2**n`` candidates and
    exactly one can match, so a stored input that no row encodes to is a
    disagreement between the committed example and ``encode_inputs`` -- and
    it is reported here rather than written as a confident wrong row.
    """
    import esolangs

    if example.fill is not None:
        return "".join(str(bit) for bit in example.bits)
    inputs = list(example.inputs)
    if not inputs:
        return "(none)"
    name = _display_name(stem)
    arity = len(example.table).bit_length() - 1
    for row in range(2**arity):
        candidate = [(row >> (arity - 1 - i)) & 1 for i in range(arity)]
        encoded = esolangs.encode_inputs(name, candidate).strip().split("\n")
        if encoded == inputs:
            return "".join(str(b) for b in candidate)
    raise AssertionError(
        f"{stem}: no input row encodes to {inputs!r}; the committed example "
        f"and encode_inputs disagree"
    )


def boolean_manifest_text() -> str:
    """Return the table saying what each committed boolean program computes.

    A committed program is a *sample*: one truth table at one input row.
    Neither fact is recoverable from the file -- these languages have no
    comment syntax to carry them -- so without this table a reader can run
    an example but cannot tell whether its output is right, which is the
    only thing an example is for.  Generated from the same entries the
    programs are, so the two cannot disagree.
    """
    rows = [
        "# What each boolean example computes",
        "",
        "Generated by `scripts/generate.py examples` with `balance=True`; do not",
        "edit by hand. Filenames are dash-separated display names (`cvnc.txt` is",
        "`CV(N)(C)`); pass the Language column to `esolangs run`, which ignores case.",
        "",
        "Each program samples one truth table at one input row. Stdin formats",
        "vary; use `esolangs.encode_inputs(language, bits)`. Template programs",
        "embed their inputs and read no stdin.",
        "",
        "Row gives the logical bits; Input gives their language-specific encoding.",
        "",
        "| Program | Language | Table | Row | Input | Expected output |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for stem, example in sorted(BOOLEAN_EXAMPLES.items()):
        if example.fill is not None:
            given = "embedded " + "".join(str(b) for b in example.bits)
        else:
            given = " ".join(example.inputs) or "(none)"
        row = _logical_row(stem, example)
        if not example.expected_compared:
            expected = "not the answer -- see note"
        else:
            expected = repr(example.expected) if example.expected else "(nothing)"
        rows.append(
            f"| `{example.filename}` | {_display_name(stem)} | `{example.table}` | "
            f"`{row}` | {given} | {expected} |"
        )
    if any(e.note for e in BOOLEAN_EXAMPLES.values()):
        rows += ["", "## Notes", ""]
        for stem, example in sorted(BOOLEAN_EXAMPLES.items()):
            if example.note:
                rows.append(f"- **{stem}** -- {example.note}")
    return "\n".join(rows) + "\n"


def write_boolean_manifest() -> None:
    """Write the manifest to disk.

    Split from the text so a test can compare the committed file against
    what this would produce without regenerating every program to find
    out.  Nothing checked the manifest at all until then, so a note added
    to a language left the committed table describing the one before it.
    """
    path = EXAMPLES / "MANIFEST.md"
    path.write_text(boolean_manifest_text(), encoding="utf-8")
    print(f"wrote     examples/{path.name}")


SETS = {
    "boolean": boolean_programs,
}


def write_set(name: str) -> None:
    """Write one example directory from its generators, reporting each file."""
    directory = EXAMPLES
    directory.mkdir(parents=True, exist_ok=True)
    for stem, generated in SETS[name]():
        suffix = ".png" if isinstance(generated, Raster) else ".txt"
        path = directory / f"{stem}{suffix}"
        # Text files retain a final POSIX newline; PNGs retain their bytes.
        program = (
            generated.to_png()
            if isinstance(generated, Raster)
            else (generated.rstrip("\n") + "\n").encode("utf-8")
        )
        existing = path.read_bytes() if path.exists() else None
        path.write_bytes(program)
        status = "unchanged" if existing == program else "wrote"
        print(f"{status:9} examples/{path.name}")
    if name == "boolean":
        write_boolean_manifest()


def main() -> int:
    """Write every requested example set from its generators."""
    parser = argparse.ArgumentParser(description="Write the committed examples")
    parser.add_argument(
        "sets",
        nargs="*",
        choices=list(SETS),
        # No default: argparse validates a default list against ``choices``
        # as if it were a single value, so an empty ``sets`` means "all".
        help="example sets to write (default: all)",
    )
    args = parser.parse_args()
    for name in args.sets or SETS:
        write_set(name)
    return 0
