"""Regenerate the committed ZTOALC L anchor table.

The generator puts command ``j`` on the ``j``-th smallest trajectory value at
or below ``_MAX_LINES``, so a program of ``L`` commands is exactly as long as
its anchor's ``L``-th smallest usable value.  The table is that argmin:

1. a stopping-time sieve to 10**7 yields the Collatz delay records (OEIS
   A006877) -- a candidate pool, derived here rather than cited;
2. for each length ``L``, the pool member minimizing that value plus the
   digits of the start (line 1 carries it), ties keeping the incumbent so
   equal runs coalesce into one ``(end, start)`` row.

The argmin is exact over the pool, not over every start: a full sweep would
need the sorted usable values of all 2**22 candidates.  Delay records are
only a cheap stand-in -- they win by dipping low often, not by running long,
which is why the three records past the sieve are absent (9780657630 keeps
157 usable values against 511935's 386, so no length would ever pick them).

Usage:
    python scripts/generate.py ztoalc            # rewrite ztoalc_starts.py
    python scripts/generate.py ztoalc --check    # verify the table and capacity record
"""

import sys
from array import array
from pathlib import Path

from esolangs.tools.ztoalc_l import _MAX_LINES, _usable_values

ROOT = Path(__file__).resolve().parents[3]

OUT = ROOT / "src/esolangs/tools/ztoalc_starts.py"

SIEVE_LIMIT = 10_000_000


def collatz_length_table(limit: int) -> list[int]:
    """Compute stopping times for every start up to ``limit`` (zero unknown)."""
    lengths = [0] * (limit + 1)
    lengths[1] = 0

    for start in range(2, limit + 1):
        if lengths[start]:
            continue

        path = []
        value = start
        while value > 1 and (value > limit or not lengths[value]):
            path.append(value)
            value = value // 2 if value % 2 == 0 else 3 * value + 1

        length = lengths[value] if value <= limit else 0
        for value in reversed(path):
            length += 1
            if value <= limit:
                lengths[value] = length

    return lengths


def delay_records(limit: int) -> list[int]:
    """Collect starts up to ``limit`` beating every smaller stopping time."""
    lengths = collatz_length_table(limit)
    records = []
    best = -1
    for start in range(1, limit + 1):
        if lengths[start] > best:
            best = lengths[start]
            records.append(start)
    return records


def anchors() -> list[tuple[int, int]]:
    """Derive the length-interval start table by the argmin above."""
    usable = {
        s: sorted(_usable_values(s, _MAX_LINES)) for s in delay_records(SIEVE_LIMIT)
    }

    table: list[tuple[int, int]] = []
    for length in range(1, max(len(v) for v in usable.values()) + 1):
        # the emitted program is the last line plus line 1's start value, so a
        # longer start can lose a shorter trajectory (L=21: 25@58 beats 77031@56)
        cost = {
            s: v[length - 1] + len(str(s))
            for s, v in usable.items()
            if len(v) >= length
        }
        floor = min(cost.values())
        held = table[-1][1] if table else None
        # ties keep the incumbent, so a run of lengths coalesces into one row
        best = (
            held
            if held in cost and cost[held] == floor
            else min(cost, key=lambda s: (cost[s], s))
        )
        if table and table[-1][1] == best:
            table[-1] = (length, best)
        else:
            table.append((length, best))
    return table


def slot_record(cap: int) -> tuple[int, int]:
    """Return the greatest trajectory capacity at or below ``cap``."""
    counts = array("i", [0]) * (cap + 1)
    counts[2] = 1
    best, best_start = 1, 2
    for start in range(3, cap + 1):
        value, count = start, 0
        while value >= start:
            if value <= cap:
                count += 1
            value = value // 2 if value % 2 == 0 else 3 * value + 1
        counts[start] = count + counts[value]
        if counts[start] > best:
            best, best_start = counts[start], start
    return best, best_start


def write_module(table: list[tuple[int, int]]) -> None:
    """Write ``ztoalc_starts.py``."""
    lines = [
        '"""Collatz start for each ZTOALC L text-length interval.',
        "",
        "Each entry ``(end, start)`` covers every length up to ``end``: a program",
        "of ``n`` commands sits on the ``n`` smallest values of the first",
        "``start`` whose ``end >= n``.  Each row is the delay record below 10**7",
        "minimizing that length's emitted size -- last line plus the start's",
        "digits, which line 1 carries.  ``end`` is load-bearing: a row further",
        "down can have room for ``n`` and still be the larger program.",
        "",
        "Regenerated by ``scripts/generate.py ztoalc``; do not edit by hand.",
        '"""',
        "",
        "ANCHORS: list[tuple[int, int]] = [",
    ]
    for end, start in table:
        lines.append(f"    ({end}, {start}),")
    lines.append("]")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} with {len(table)} anchors")


def main() -> int:
    """Regenerate the table, or check it and the cited capacity record."""
    table = anchors()
    if "--check" in sys.argv:
        namespace: dict[str, object] = {}
        exec(OUT.read_text(), namespace)  # nosec B102 -- committed constant table
        if namespace["ANCHORS"] != table:
            print(f"[FAIL] {OUT} is stale: regenerate with {Path(sys.argv[0]).name}")
            return 1
        print(f"[ok] {OUT} matches the derived anchors ({len(table)} entries)")
        record, start = slot_record(_MAX_LINES)
        print(f"record capacity under {_MAX_LINES}: {record} (start {start})")
        if record != 395:
            print("[FAIL] the 395 cited in ztoalc_l.py and limitations.md is stale")
            return 1
        return 0
    write_module(table)
    return 0
