"""Collatz start for each ZTOALC L text-length interval.

Each entry ``(end, start)`` covers every length up to ``end``: a program
of ``n`` commands sits on the ``n`` smallest values of the first
``start`` whose ``end >= n``.  Each row is the delay record below 10**7
minimizing that length's emitted size -- last line plus the start's
digits, which line 1 carries.  ``end`` is load-bearing: a row further
down can have room for ``n`` and still be the larger program.

Regenerated by ``scripts/generate.py ztoalc``; do not edit by hand.
"""

ANCHORS: list[tuple[int, int]] = [
    (1, 2),
    (4, 3),
    (7, 6),
    (12, 9),
    (20, 18),
    (21, 25),
    (25, 703),
    (34, 54),
    (77, 129),
    (95, 171),
    (113, 313),
    (152, 6171),
    (153, 106239),
    (185, 6171),
    (195, 3711),
    (196, 10971),
    (207, 3711),
    (208, 10971),
    (212, 3711),
    (223, 10971),
    (275, 13255),
    (292, 230631),
    (386, 511935),
]
