"""Collatz start for each ZTOALC text-length interval.

Each entry ``(end, start)`` covers every text length up to ``end``: for a
length ``n`` the generator uses the first ``start`` whose ``end >= n``.  The
sieve-derived entries are the record-holders under 10**7 that achieve the
smallest trajectory peak for every length in their interval; the final three
are the known record-holders beyond the sieve (their trajectories are
verified by ``scripts/make_ztoalc_table.py``).

Regenerated by ``scripts/make_ztoalc_table.py``; do not edit by hand.
"""

ANCHORS: list[tuple[int, int]] = [
    (1, 2),
    (8, 6),
    (20, 18),
    (23, 25),
    (44, 129),
    (51, 171),
    (86, 313),
    (144, 649),
    (181, 1161),
    (216, 2919),
    (237, 3711),
    (275, 13255),
    (281, 23529),
    (385, 216367),
    (469, 511935),
    (612, 5649499),
    (664, 6649279),
    (685, 8400511),
    (949, 63728127),
    (986, 670617279),
    (1132, 9780657630),
]
