"""Text generators, grouped by language family."""

from esolangs.tools.generators.helpers import _ilog
from esolangs.tools.generators.other import (
    _123,
    clockwise,
    container,
    forth,
    home_row,
    laserfuck,
    magnitude,
    nevermind,
    nocomment,
    painfuck,
    taglate,
    unsquare,
    ztoalc,
)
from esolangs.tools.generators.register import (
    bio,
    dig,
    dotlang,
    eval,
    huf,
    polynomial,
    qoibl,
    sophie,
    wii2d,
)
from esolangs.tools.generators.stack import modulous, temporary
from esolangs.tools.generators.tape import (
    ascii_art,
    bf,
    bfstack,
    brainif,
    circlefuck,
    excon,
    mammalian,
    minifuck,
    six_five,
    suffolk,
)

__all__ = [
    "_123",
    "_ilog",
    "ascii_art",
    "bf",
    "bfstack",
    "bio",
    "brainif",
    "circlefuck",
    "clockwise",
    "container",
    "dig",
    "dotlang",
    "eval",
    "excon",
    "forth",
    "home_row",
    "huf",
    "laserfuck",
    "magnitude",
    "mammalian",
    "minifuck",
    "modulous",
    "nevermind",
    "nocomment",
    "painfuck",
    "polynomial",
    "qoibl",
    "six_five",
    "sophie",
    "suffolk",
    "taglate",
    "temporary",
    "unsquare",
    "wii2d",
    "ztoalc",
]
