[package]
name = "esolangs-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
regex = "1"

[[bin]]
name = "laserfuck"
path = "laserfuck.rs"

[[bin]]
name = "unsquare"
path = "unsquare.rs"

[[bin]]
name = "pct_squared_minus_one"
path = "pct_squared_minus_one.rs"

[[bin]]
name = "bit_tilde"
path = "bit_tilde.rs"

[[bin]]
name = "forth"
path = "forth.rs"

[[bin]]
name = "basicfuck"
path = "basicfuck.rs"

[[bin]]
name = "painfuck"
path = "painfuck.rs"

[[bin]]
name = "three_x"
path = "three_x.rs"
