"""Write the committed examples from their generators.

Every committed example is exactly what its generator produces today: the
boolean programs under ``examples/boolean`` come from the boolean generators.
``tests/scripts/test_examples.py`` asserts that; run this script to refresh
the files after a generator changes.

    python scripts/write_examples.py           # every set
    python scripts/write_examples.py boolean   # just one set
"""

import argparse
import pathlib
import sys
from collections.abc import Iterator

from esolangs.registry import LANGUAGES, canonical_id
from esolangs.tools.boolean.examples import BOOLEAN_EXAMPLES

_BY_ID = {lang.id: name for name, lang in LANGUAGES.items()}

ROOT = pathlib.Path(__file__).parents[1]
EXAMPLES = ROOT / "examples"


def boolean_programs() -> Iterator[tuple[str, str]]:
    """Yield ``(stem, program)`` for every boolean example."""
    for stem, example in sorted(BOOLEAN_EXAMPLES.items()):
        yield stem, example.build()


def _display_name(stem: str) -> str:
    """Return the registry display name for an example's filename stem."""
    return _BY_ID.get(canonical_id(stem.replace("-", " ")), stem)


def _logical_row(stem: str, example: object) -> str:
    """Return the input row as plain bits, however the language spells it.

    The Input column shows the *encoded* stdin, which made this table
    unusable for judging an example programmatically: a reader had to work
    back from ``% A`` to ``10`` for Grapheme, and from the decimal ``1`` to
    ``01`` for Fargo.  A template language already records its bits; a
    reading one does not, so the row is recovered by encoding each candidate
    and keeping the one that reproduces the stored input.

    That search is also a check.  There are only ``2**n`` candidates and
    exactly one can match, so a stored input that no row encodes to is a
    disagreement between the committed example and ``encode_inputs`` -- and
    it is reported here rather than written as a confident wrong row.
    """
    import esolangs

    bits = getattr(example, "bits", ())
    if getattr(example, "fill", None) is not None:
        return "".join(str(b) for b in bits)
    inputs = list(getattr(example, "inputs", ()))
    if not inputs:
        return "(none)"
    name = _display_name(stem)
    arity = len(example.table).bit_length() - 1  # type: ignore[attr-defined]
    for row in range(2**arity):
        candidate = [(row >> (arity - 1 - i)) & 1 for i in range(arity)]
        encoded = esolangs.encode_inputs(name, candidate).strip().split("\n")
        if encoded == inputs:
            return "".join(str(b) for b in candidate)
    raise AssertionError(
        f"{stem}: no input row encodes to {inputs!r}; the committed example "
        f"and encode_inputs disagree"
    )


def write_boolean_manifest() -> None:
    """Write the table saying what each committed boolean program computes.

    A committed program is a *sample*: one truth table at one input row.
    Neither fact is recoverable from the file -- these languages have no
    comment syntax to carry them -- so without this table a reader can run
    an example but cannot tell whether its output is right, which is the
    only thing an example is for.  Generated from the same entries the
    programs are, so the two cannot disagree.
    """
    rows = [
        "# What each boolean example computes",
        "",
        "Generated by `scripts/write_examples.py`; do not edit by hand.",
        "",
        "Each program is one truth table sampled at one input row. An",
        "input-reading program takes its bits on stdin -- in the shape the",
        "Input column shows, which is not `0`/`1` lines for every language",
        "-- while a template program has them embedded and reads nothing.",
        "`esolangs.encode_inputs(language, bits)` builds the right stdin",
        "for any of them.",
        "",
        "The Row column is the logical input bits; the Input column is how",
        "that row is actually spelled for the language.",
        "",
        "| Program | Language | Table | Row | Input | Expected output |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for stem, example in sorted(BOOLEAN_EXAMPLES.items()):
        if example.fill is not None:
            given = "embedded " + "".join(str(b) for b in example.bits)
        else:
            given = " ".join(example.inputs) or "(none)"
        row = _logical_row(stem, example)
        if not example.expected_compared:
            expected = "not the answer -- see note"
        else:
            expected = repr(example.expected) if example.expected else "(nothing)"
        rows.append(
            f"| `{stem}.txt` | {_display_name(stem)} | `{example.table}` | "
            f"`{row}` | {given} | {expected} |"
        )
    if any(e.note for e in BOOLEAN_EXAMPLES.values()):
        rows += ["", "## Notes", ""]
        for stem, example in sorted(BOOLEAN_EXAMPLES.items()):
            if example.note:
                rows.append(f"- **{stem}** -- {example.note}")
    path = EXAMPLES / "boolean" / "MANIFEST.md"
    path.write_text("\n".join(rows) + "\n", encoding="utf-8")
    print(f"wrote     examples/boolean/{path.name}")


SETS = {
    "boolean": boolean_programs,
}


def write_set(name: str) -> None:
    """Write one example directory from its generators, reporting each file."""
    directory = EXAMPLES / name
    directory.mkdir(parents=True, exist_ok=True)
    for stem, generated in SETS[name]():
        path = directory / f"{stem}.txt"
        # The file is the generator's output plus a final newline, so it is
        # a well-formed text file; the sync test compares after stripping
        # that newline, exactly as the interpreters do when running it.
        program = generated.rstrip("\n") + "\n"
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        path.write_text(program, encoding="utf-8")
        status = "unchanged" if existing == program else "wrote"
        print(f"{status:9} examples/{name}/{stem}.txt")
    if name == "boolean":
        write_boolean_manifest()


def main() -> int:
    """Write every requested example set from its generators."""
    parser = argparse.ArgumentParser(description="Write the committed examples")
    parser.add_argument(
        "sets",
        nargs="*",
        choices=list(SETS),
        # No default: argparse validates a default list against ``choices``
        # as if it were a single value, so an empty ``sets`` means "all".
        help="example sets to write (default: all)",
    )
    args = parser.parse_args()
    for name in args.sets or SETS:
        write_set(name)
    return 0


if __name__ == "__main__":
    sys.exit(main())
